# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", None)

# Games data
# EDA

In [5]:
games = pd.read_csv("/Users/tativalentine/Documents/GitHub/games_raw.csv", index_col="id")

In [6]:
games.head()

,date,home_team_score,period,postseason,season,status,time,visitor_team_score,home_team.id,home_team.abbreviation,home_team.city,home_team.conference,home_team.division,home_team.full_name,home_team.name,visitor_team.id,visitor_team.abbreviation,visitor_team.city,visitor_team.conference,visitor_team.division,visitor_team.full_name,visitor_team.name
id,,,,,,,,,,,,,,,,,,,,,,
47179,2019-01-30T00:00:00.000Z,126,4,False,2018,Final,,94,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets
48751,2019-02-09T00:00:00.000Z,112,4,False,2018,Final,,123,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,13,LAC,LA,West,Pacific,LA Clippers,Clippers
48739,2019-02-08T00:00:00.000Z,117,4,False,2018,Final,,110,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets
48740,2019-02-08T00:00:00.000Z,119,4,False,2018,Final,,106,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers
48746,2019-02-08T00:00:00.000Z,102,4,False,2018,Final,,96,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,16,MIA,Miami,East,Southeast,Miami Heat,Heat

In [7]:
# time column is empty
games.drop("time", axis=1, inplace=True)

In [8]:
# dropping a random unfinished game
games.drop(games[games["status"].eq("8:30 PM ET")].index, axis=0, inplace=True)

In [9]:
# dropping unplayed games
games.drop(games[games["home_team_score"].eq(0)].index, axis=0, inplace=True)

In [10]:
# dropping unecessary name info
games.drop(["home_team.city", "visitor_team.city", "home_team.name", "visitor_team.name"], axis=1, inplace=True)

In [11]:
games.head()

,date,home_team_score,period,postseason,season,status,visitor_team_score,home_team.id,home_team.abbreviation,home_team.conference,home_team.division,home_team.full_name,visitor_team.id,visitor_team.abbreviation,visitor_team.conference,visitor_team.division,visitor_team.full_name
id,,,,,,,,,,,,,,,,,
47179,2019-01-30T00:00:00.000Z,126,4,False,2018,Final,94,2,BOS,East,Atlantic,Boston Celtics,4,CHA,East,Southeast,Charlotte Hornets
48751,2019-02-09T00:00:00.000Z,112,4,False,2018,Final,123,2,BOS,East,Atlantic,Boston Celtics,13,LAC,West,Pacific,LA Clippers
48739,2019-02-08T00:00:00.000Z,117,4,False,2018,Final,110,23,PHI,East,Atlantic,Philadelphia 76ers,8,DEN,West,Northwest,Denver Nuggets
48740,2019-02-08T00:00:00.000Z,119,4,False,2018,Final,106,30,WAS,East,Southeast,Washington Wizards,6,CLE,East,Central,Cleveland Cavaliers
48746,2019-02-08T00:00:00.000Z,102,4,False,2018,Final,96,26,SAC,West,Pacific,Sacramento Kings,16,MIA,East,Southeast,Miami Heat

In [12]:
games.to_csv("/Users/tativalentine/Documents/GitHub/games_clean.csv")

# Stats data

##### This data is used to build the model

In [13]:
stats = pd.read_csv("/Users/tativalentine/Documents/GitHub/stats_raw.csv", index_col="id")

/var/folders/nf/rr1y3sz51_d8gbgc735ltjtc0000gn/T/ipykernel_19563/3974129964.py:1: DtypeWarning: Columns (13,36) have mixed types. Specify dtype option on import or set low_memory=False.
  stats = pd.read_csv("/Users/tativalentine/Documents/GitHub/stats_raw.csv", index_col="id")

In [14]:
stats.head(2)

,ast,blk,dreb,fg3_pct,fg3a,fg3m,fg_pct,fga,fgm,ft_pct,fta,ftm,min,oreb,pf,pts,reb,stl,turnover,game.id,game.date,game.home_team_id,game.home_team_score,game.period,game.postseason,game.season,game.status,game.time,game.visitor_team_id,game.visitor_team_score,player.id,player.first_name,player.height_feet,player.height_inches,player.last_name,player.position,player.team_id,player.weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1069008,0.0,1.0,2.0,0.2,5.0,1.0,0.333,9.0,3.0,0.0,0.0,0.0,20:08,0.0,0.0,7.0,2.0,0.0,2.0,45237,2019-01-17T00:00:00.000Z,4,114,4,False,2018,Final,,26,95,415,Iman,6.0,5.0,Shumpert,G,3,215.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings
1069009,4.0,0.0,5.0,0.0,2.0,0.0,0.200,5.0,1.0,0.0,0.0,0.0,19:22,1.0,1.0,2.0,6.0,0.0,0.0,45237,2019-01-17T00:00:00.000Z,4,114,4,False,2018,Final,,26,95,49,Nemanja,6.0,10.0,Bjelica,F,10,234.0,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings

In [16]:
# drop uneeded columns
stats.drop(["game.period", "game.postseason", "game.status", "game.time", "player.height_feet", "player.height_inches",
            "player.weight_pounds", "team.abbreviation", "team.city", "team.conference", "team.division", "team.name",
            "player.id", "player.first_name", "player.last_name", "player.position", "team.full_name", "player.team_id"],
          axis=1, inplace=True)

In [17]:
# a null value generally indicates that the player did not play in that game
stats.dropna(axis=0, how="any", inplace=True)

In [18]:
# clean time column to get a consitent format. ("mm:ss" or "m:ss")
stats["min"] = stats["min"].astype(str)

# drop the row if the player didn't play in the game
played_0min = stats[stats["min"].eq("0:00") | stats["min"].str.startswith("0") | stats["min"].eq("")].index
stats.drop(played_0min, axis=0, inplace=True)

# Convert times like "27.0" to "27:0"
stats["min"] = stats["min"].str.replace(".",":")

# convert times like "27" to "27:00"
minutes_only_times = stats["min"][~stats["min"].str.contains(":")].index
stats["min"].loc[minutes_only_times] += ":00"


minutes = [time[0] for time in stats["min"].str.split(":").values]
seconds = [time[1] for time in stats["min"].str.split(":").values]

# convert times like "27:0" to "27:00"
for i, second in enumerate(seconds):
    if len(second) == 1:
        seconds[i] = second + "0"

# convert times like "8:60" to "9:00"
for i, second in enumerate(seconds):        
    if second == "60":
        seconds[i] = "00"
        minutes[i] = str(int(minutes[i]) + 1)  # increment minutes by 1

times = [":".join(list(item)) for item in list(zip(minutes,seconds))]

stats["min"] = times

/var/folders/nf/rr1y3sz51_d8gbgc735ltjtc0000gn/T/ipykernel_19563/2667877961.py:9: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  stats["min"] = stats["min"].str.replace(".",":")
/var/folders/nf/rr1y3sz51_d8gbgc735ltjtc0000gn/T/ipykernel_19563/2667877961.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stats["min"].loc[minutes_only_times] += ":00"

In [19]:
stats

,ast,blk,dreb,fg3_pct,fg3a,fg3m,fg_pct,fga,fgm,ft_pct,fta,ftm,min,oreb,pf,pts,reb,stl,turnover,game.id,game.date,game.home_team_id,game.home_team_score,game.season,game.visitor_team_id,game.visitor_team_score,team.id
id,,,,,,,,,,,,,,,,,,,,,,,,,,,
1069008,0.0,1.0,2.0,0.200,5.0,1.0,0.333,9.0,3.0,0.000,0.0,0.0,20:08,0.0,0.0,7.0,2.0,0.0,2.0,45237,2019-01-17T00:00:00.000Z,4,114,2018,26,95,26
1069009,4.0,0.0,5.0,0.000,2.0,0.0,0.200,5.0,1.0,0.000,0.0,0.0,19:22,1.0,1.0,2.0,6.0,0.0,0.0,45237,2019-01-17T00:00:00.000Z,4,114,2018,26,95,26
1069010,4.0,1.0,5.0,0.000,0.0,0.0,0.667,6.0,4.0,0.000,0.0,0.0,27:24,6.0,2.0,8.0,11.0,3.0,2.0,45237,2019-01-17T00:00:00.000Z,4,114,2018,26,95,26
1069011,1.0,0.0,1.0,0.545,11.0,6.0,0.500,18.0,9.0,0.000,0.0,0.0,32:06,0.0,2.0,24.0,1.0,2.0,0.0,45237,2019-01-17T00:00:00.000Z,4,114,2018,26,95,26
1069012,8.0,1.0,5.0,0.000,2.0,0.0,0.400,10.0,4.0,0.667,3.0,2.0,30:30,0.0,4.0,10.0,5.0,1.0,4.0,45237,2019-01-17T00:00:00.000Z,4,114,2018,26,95,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293372,0.0,0.0,1.0,0.000,0.0,0.0,0.286,7.0,2.0,0.667,3.0,2.0,21:10,0.0,3.0,6.0,1.0,0.0,0.0,13561,2001-03-20T00:00:00.000Z,6,75,2000,20,110,6
293373,5.0,0.0,0.0,0.667,3.0,2.0,0.500,8.0,4.0,1.000,2.0,2.0,14:54,0.0,2.0,12.0,0.0,0.0,1.0,13561,2001-03-20T00:00:00.000Z,6,75,2000,20,110,6
293374,0.0,0.0,0.0,0.000,0.0,0.0,0.000,1.0,0.0,0.000,0.0,0.0,6:29,0.0,0.0,0.0,0.0,0.0,1.0,13561,2001-03-20T00:00:00.000Z,6,75,2000,20,110,6
293376,7.0,4.0,4.0,0.000,4.0,0.0,0.313,16.0,5.0,0.333,6.0,2.0,41:21,7.0,2.0,12.0,11.0,2.0,4.0,13863,2001-03-20T00:00:00.000Z,5,95,2000,22,103,22
293377,4.0,2.0,6.0,0.000,0.0,0.0,0.200,5.0,1.0,0.500,2.0,1.0,33:16,3.0,4.0,3.0,9.0,6.0,4.0,13863,2001-03-20T00:00:00.000Z,5,95,2000,22,103,22

In [20]:
stats.to_csv("/Users/tativalentine/Documents/GitHub/stats_clean.csv")